# IOCS can use a PVC as a data volume, or mount the host filesystem
{{- if .Values.dataVolume.pvc }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-data
  labels:
    app: {{ .Chart.Name }}
    beamline: {{ .Values.beamline }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
{{- end }}
