# default values for all IOCs on bl38p
# see end of file for values that may be overriden per individual IOC

beamline: bl38p
# we use the default service account in the namespace so leave this out
# if you need to specify an alternative then uncomment below
# serviceAccountName: k8s-p38-iocs

# useHostNetwork - use host network for IOC - required for Channel Access
# to work outside of the cluster
hostNetwork: true

# useAffinity - only run on nodes with label beamline:bl45p
# Not using this now that we have cluster per beamline
# However if you are using one cluster for multiple beamlines / domains
# Then label the local nodes for each beamline and switch to true
useAffinity: false

# root folder for ioc source/binaries inside generic IOC container
iocFolder: /epics/ioc
iocConfig: /epics/ioc/config
# scripts for controlling the IOC
start: /epics/ioc/start.sh
stop: /epics/ioc/stop.sh
liveness: /epics/ioc/liveness.sh

# the following are added to the pod's environment
globalenv:
  # Where to find RTEMS IOC files
  - name: "K8S_IOC_TFTP_ADDR"
    value: "172.23.168.220"
  - name: "K8S_IOC_TFTP_PORT"
    value: "69"
  - name: "K8S_IOC_NFS_MOUNT"
    value: "172.23.168.220:iocs"

# reasonable defaults for securityContext
securityContext:
  allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

########################################################################################
# The following values are expected to be overridden in individual IOC values.yaml
########################################################################################

# this value is the only mandatory override
# note that the configuration for the generic IOC is provided by placing its
# config folder into beamline-chart/config. When the chart is packaged, the
# template
image:

# provide a PVC for autosave
autosave: true

# Somewhere to mount at /data if needed
dataVolume:
  # A PVC to write data into
  pvc: true
  # A path on the host machine to write data into, ignored if dataVolume.pvc is true
  hostPath: ""

# use the shared PV for publishing opi files over http (see services/opis)
opisClaim: bl38p-opis-opi-claim


# default resource limits
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi
